### ISSUE TITLE
Exception ao tentar rodar o exemplo

### ISSUE THREAD

**Issue by almeidaalex** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#11]
Olá Devs, baixei essa versão para testar o desenvolvimento na LIO, após baixar e compilar, tomei a seguinte exception

`FATAL EXCEPTION: main
Process: cielo.ordermanager.sdk.sample, 
PID: 6372 java.lang.RuntimeException: Unable to start activity ComponentInfo{cielo.ordermanager.sdk.sample/cielo.ordermanager.sdk.sample.ParcialPaymentActivity}: android.content.pm.PackageManager$NameNotFoundException: cielo.launcher`

Não fiz nenhuma alteração no código, simplesmente diz não encontrar uma Activity

**Comment by Stheferri** [comment]
Bom dia Alex.
Por gentileza, me informe seu e-mail.
Obrigada.

Att,
Cielo Technical Partner

**Comment by almeidaalex** [comment]
adeno.si@gmail.com

**Comment by haroldolivieri** [comment]
Resolvida na #13
