### ISSUE TITLE
Erro android.content.pm.PackageManager$NameNotFoundException: cielo.launcher

### ISSUE THREAD

**Issue by xicocaio** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#13]
Estou usando a versão 0.11.5-dev da dependência da SDK e ainda persiste o problema que foi dado como closed na issue #1 .

O problema não está resolvido, e analisando o source code da classe OrderManager, dá pra ver que no construtor OrderManager, na linha 378 o código

`PackageInfo packageInfo = context.getPackageManager().getPackageInfo("cielo.launcher", 0);`

tenta buscar o package pelo nome 'cielo.launcher', que aparentemente não existe.

Não conheço os detalhes da implementação e não sei se o pacote 'cielo.launcher' deveria existir, mas se isto foi um engano com o nome do pacote, sugiro usar o método `getPackageName()` que evitaria erros deste tipo. Ex:

`PackageInfo packageInfo = context.getPackageManager().getPackageInfo(getPackageName(), 0);`

**Comment by Stheferri** [comment]
Boa tarde,

Por favor, nos envie um endereço de e-mail válido.

Atenciosamente,
Cielo Technical Partner

**Comment by xicocaio** [comment]
Olá,

Meu e-mail é xicocaio@gmail.com.

Abs

**Comment by haroldolivieri** [comment]
Esse erro ocorre porque você está rodando sua aplicação em um emulador ou device que não é a LIO.
Para testar essa biblioteca é necessário utilizar o emulador da LIO para ambiente de sandbox, como é definido na documentaçao da [Integação Local](https://desenvolvedores.cielo.com.br/api-portal/pt-br/content/cielo-lio-integracao-local)

Faça o download desse [apk](http://cm.gy/3y2j) e instale no device que está testando sua aplicação.
