### ISSUE TITLE
Erro ao executar o projeto

### ISSUE THREAD

**Issue by psborges84** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#14]
Atualmente estou utilizando a biblioteca versão 'compile 'com.cielo.lio:order-manager:0.11.9' do lio, funciona perfeitamente esta versão, mas eu atualizei para a nova versão 'compile 'com.cielo.lio:order-manager:0.14.0', baixando o projeto e configurando do zero no android studio. Quando vou executar o projeto para rodar no smartfone acontece o seguinte erro,

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK kotlin/annotation/annotation.kotlin_builtins
	File1: C:\Program Files\Android\Android Studio\gradle\m2repository\org\jetbrains\kotlin\kotlin-runtime\1.0.5\kotlin-runtime-1.0.5.jar
	File2: C:\Users\XXX\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.1.3\e51ebc59da5103a2052859e89682c7f9c3456298\kotlin-stdlib-1.1.3.jar

Já tentei de todas as formas, já desinstalei o android studio. E nada.

**Comment by Stheferri** [comment]
Prezado, boa tarde!

Por favor, poderia nos fornecer um endereço de e-mail?

Att,
Cielo Technical Partner
