### ISSUE TITLE
Erro no Retorno do Pagamento - Integração Local

### ISSUE THREAD

**Issue by MarceloPinto** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#15]
Caros, 
Integramos o módulo de pagamento da LIO no nosso aplicativo, mas estamos tendo uma dificuldade:

Seguimos o passo a passo para integração local indicado na página de desenvolvedores Cielo. O pagamento é realizado com sucesso, e inclusive conseguimos recuperar os dados referentes a ele.

O problema é: Após o pagamento voltamos para a tela do nosso app, tanto utilizando o emulador LIO quanto a própria máquina que temos para teste, mas se sairmos dessa tela ocorre um erro que em seguida causa um crash na aplicação:

> E/ActivityThread: Activity br.com.activity.***********Activity has leaked IntentReceiver cielo.sdk.order.v1.OrderManagerImplv1$CancellationBroadcastReceiver@1370528 that was originally registered here. Are you missing a call to unregisterReceiver()?

O Android Studio indica como causadora do erro a seguinte linha: _**orderManager.placeOrder(order);**_

O erro menciona o BroadcastReceiver, apesar de em nenhum momento instanciarmos o mesmo.

Podem ajudar?

Att,
Marcelo Faustino
marcelo.faustino@comlurb.rio.rj.gov.br

![erro3](https://user-images.githubusercontent.com/16604450/30500440-ae574606-9a34-11e7-8d8b-c91539f48b77.JPG)

**Comment by psborges84** [comment]
Marcelo, saiu alguma atualização da sdk e do emulador? Conseguiu resolver o problema?

**Comment by MarceloPinto** [comment]
Não saiu atualização e ainda não resolvi.

O erro ocorre na ultima versão do sdk disponibilizada na página de desenvolvedores da Cielo, que é a _compile 'com.cielo.lio:order-manager:0.14.1'_.

Recebi um contato direto informando que a solicitação está sendo atendida pela equipe responsável e pedindo pra aguardar um contato. Sigo no aguardo...

**Comment by psborges84** [comment]
o erro está no emulador do lio. até agora eles não disponibilizaram uma versão que corrige este problema.

**Comment by psborges84** [comment]
Marcelo, alguma solução?

**Comment by rafaelwkerr** [comment]
Bom dia pessoal, sou Dev no time da LIO, não trabalhei no SDK, mas assim que chegar vou ver com o pessoal responsável se consigo ajudar nessa solução e hoje ainda respondo vocês aqui na thread.

**Comment by psborges84** [comment]
@rafaelwkerr obrigado, estou com dois tickets em aberto desde a semana passada no fórum de desenvolvedores da cielo. me parece que é um erro do sdk. ainda não recebi nenhuma previsão de solução.

**Comment by psborges84** [comment]
@MarceloPinto ok, qualquer novidade posta ai.

**Comment by psborges84** [comment]
atualizaram a versão

compile 'com.cielo.lio:order-manager:0.14.4'

mesmo assim o erro continua, agora apareceu outros bugs cabrosos.

aff

**Comment by psborges84** [comment]
compile 'com.cielo.lio:order-manager:0.14.5'

continua com os mesmos erros

**Comment by MarceloPinto** [comment]
@psborges84, também estou com a versão compile 'com.cielo.lio:order-manager:0.14.5'.

Consegui tratar todos os bugs diferentes que apareceram, mas o o primeiro erro continua acontecendo da mesma forma...

**Comment by haroldolivieri** [comment]
@MarceloPinto o erro persiste? Pode testar com a nova versão da lib 0.17.7-beta?
