### ISSUE TITLE
erro ao executar a opção pagamento parcelado.

### ISSUE THREAD

**Issue by psborges84** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#17]
ao executar o projeto, utilizando a opção pagamento parcelado da a seguinte mensagem

"essa funcionalidade não esta disponível nessa versão da lio".

estou utilizando o emulador https://s3-sa-east-1.amazonaws.com/cielo-lio-store/apps/lio-emulator/1.0.0/lio-emulator.apk conforme o site.

existe alguma atualização do emulador?

**Comment by haroldolivieri** [comment]
@psborges84 o erro persiste? Pode testar com a nova versão da lib 0.17.7-beta?
