### ISSUE TITLE
android.content.pm.PackageManager$NameNotFoundException: cielo.launcher

### ISSUE THREAD

**Issue by FelipeRsN** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#19]
Boa noite, tentei de tudo usar o OrderManager mas quando tento instancia-lo ele ocasiona nesse erro, tanto na minha aplicação quanto nessa de exemplo do GitHub, alguma solução? Desenvolvimento da empresa esta parado aguardando esse problema.

Email para contato: felipe.rsneves@gmail.com

**Comment by haroldolivieri** [comment]
Duplicada #13
