### ISSUE TITLE
bug retorno de pagamento

### ISSUE THREAD

**Issue by psborges84** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#21]
Erro ao no retorno do método

public void onPayment(@NonNull Order retornoPagamentoCieloLIO) { 
orderPagamento = retornoPagamentoCieloLIO; 
orderPagamento.markAsPaid(); 
orderManager.updateOrder(orderPagamento); 
resetStateCieloLIO(); 
}

Estou tendo problemas no retorno deste método, a chamada funciona corretamente, eu consigo passar o cartão, informar a senha, enviar o email como comprovante, mas na hora que retiro o cartão a integração teria que chamar este método acima, para eu obter o retorno e prosseguir o fluxo da aplicação. No retorno trava tudo, da tela preta... fica em loop infinito, para resolver tenho que matar o processo do meu aplicativo.

Eu testei também, a última versão do aplicativo para integração local que está no github, (LIO SDK Sample)

@Override 
public void onPayment(@NonNull Order paidOrder) { 
Log.d(TAG, "ON PAYMENT");

order = paidOrder; 
order.markAsPaid(); 
orderManager.updateOrder(order);

resetState(); 
}

O aplicativo faz o fluxo normalmente (inserir o cartão, informar a senha, da autorizado), mas na hora de retornar os dados do recebimento (chamar o método acima) a aplicação da a seguinte mensagem "O aplicativo SDK Teste parou de funcionar" ..... Desta forma não marca a transação como paga. ou seja não executa o método acima.

Em ambos os projetos estou utilizando as credenciais de produção. usuário e senha.

Versão do Cielo Mobile 
1.17.30

Versão da Launcher 
1.24.10 (Produção)

Ambos os projetos estou utilizando a ultima versão da order manager
compile 'com.cielo.lio:order-manager:0.17.12'

**Comment by haroldolivieri** [comment]
@psborges84 qual versão da sua LIO?

**Comment by psborges84** [comment]
versão 2

**Comment by haroldolivieri** [comment]
@psborges84 iremos publicar uma nova versão, ainda hoje, corrigindo esse bug e te aviso por aqui mesmo. Obrigado pelo feedback!

**Comment by psborges84** [comment]
@haroldolivieri obrigado! no aguardo

**Comment by psborges84** [comment]
previsão?

**Comment by haroldolivieri** [comment]
@psborges84 estamos fazendo alguns testes, mas pretendemos liberar em pouco tempo.

**Comment by haroldolivieri** [comment]
@psborges84 pode testar a versão 0.17.13 e ver se o seu problema foi resolvido?

**Comment by psborges84** [comment]
@haroldolivieri momento

**Comment by psborges84** [comment]
@haroldolivieri funcionou. mas estou com outro problema.

**Comment by psborges84** [comment]
estou tentando chamar esse método

ResultOrders orders = orderManager.retrieveOrders(200, 0);

só que acontece a seguinte exception

attempt to invoke virtual method 'java.util.List cielo.orders.domain.Order.getPayments()' on a null object reference

**Comment by haroldolivieri** [comment]
@psborges vi que abri outra issue, portanto irei fechar essa e marcar como resolved. Te darei suporte pela outra issue.
