### ISSUE TITLE
SDK permite que eu busque informações do estabelecimento?

### ISSUE THREAD

**Issue by bizcap** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#24]
Eu consigo usar o SDK para buscar informações do estabelecimento como: CNPJ, Razão Social, endereço, etc? Ou conseguiria fazer via API?

**Comment by SthefaniaMFerri** [comment]
O SDK não tem essa funcionalidade, com o SDK só é possível recuperar o EC, Versão da LIO e o Nível de bateria. Todos através do InfoManager.
