### ISSUE TITLE
erro no sdk com.cielo.lio:order-manager:0.17.14

### ISSUE THREAD

**Issue by psborges84** [DeveloperCielo/LIO-SDK-Sample-Integracao-Local#25]
baixei o projeto limpo do github para testar a versão 0.17.14 do sdk. alterei para as minhas credenciais, compilei, gerei o apk. o app não consegue fazer o bind

"serviço de ordem ainda não recebeu retorno do método bind(). Verifique sua internet e tente novamente"

não funciona nada!

**Comment by arceliver** [comment]
Também estou tendo o mesmo problema.

**Comment by RIcardoBove** [comment]
Estou tentando criar o orderManager.createDraftOrder(referencia do pedido), estou tomando  o erro,  kotlin.KotlinNullPointerException
